#!/bin/bash

function die() {
  echo ERROR "$@" >&2
  exit 1
}

for i in {1..50};
do
  if [[ $(/sbin/ping -q -c 1 google.com &>/dev/null; /bin/echo $?) != 0 || $(/usr/bin/who | /usr/bin/grep console | /usr/bin/awk '{ print $1 }') == 'root' ]]; then
    if [ $i -gt 45 ]; then die "No connection to the interwebs or console stuck on root"; fi
    sleep 10
  else
    break
  fi
done

ansible_bin='/usr/local/chordata/ansible/bin'

if [ ! -e $ansible_bin/ansible ]; then
  /usr/local/chordata/anatidaSetup
fi

if [[ -n $($ansible_bin/pip list -o | grep ansible) ]]; then
  $ansible_bin/pip freeze --local | grep -v '^\-e' | cut -d = -f 1  | xargs $ansible_bin/pip install -U
fi

PATH=/usr/local/chordata/ansible/bin:$PATH
ansible-pull \
    --url=$1 \
    --inventory=localhost, \
    --directory=/usr/local/chordata/anatida

exit 0
